### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by rete** [DQM4HEP/DQM4HEP#2]
Here is the compilation error I have after commit : 

commit 7ee3b0f53cf77a457011adbb5894df730b2ed394
Author: Antoine Pingault <antoine.pingault@gmail.com>
Date:   Mon Jan 18 13:55:50 2016 +0100

    Fixed: "#Define private public" causes error with Clang 7.0+
    Added: Find Dim,DimJC,JsonCPP if already installed locally
    Added: More instruction to compile successfully Dim on mac

Following the message above, it seems that DIMJC is not installed : 

Scanning dependencies of target DQMViz
[ 66%] Creating directories for 'DQMViz'
[ 66%] Performing download step (git clone) for 'DQMViz'
Clonage dans 'DQMViz'...
remote: Counting objects: 163, done.
remote: Compressing objects: 100% (18/18), done.
remote: Total 163 (delta 6), reused 0 (delta 0), pack-reused 145
Réception d'objets: 100% (163/163), 238.66 KiB | 0 bytes/s, fait.
Résolution des deltas: 100% (44/44), fait.
Vérification de la connectivité... fait.
Note: checking out 'v01-02-00'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

HEAD est maintenant sur 4259768... CMakeLists.txt updated with correct version. Tag v01-02-00 need to be updated
[ 66%] No patch step for 'DQMViz'
[ 66%] Performing update step (git fetch) for 'DQMViz'
HEAD est maintenant sur 4259768... CMakeLists.txt updated with correct version. Tag v01-02-00 need to be updated
[ 66%] Performing configure step for 'DQMViz'
-- The C compiler identification is GNU
-- The CXX compiler identification is GNU
-- Check for working C compiler: /home/rete/soft/ilcsoft/v01-17-08/cernlib/usr/bin/gcc
-- Check for working C compiler: /home/rete/soft/ilcsoft/v01-17-08/cernlib/usr/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /home/rete/soft/ilcsoft/v01-17-08/cernlib/usr/bin/c++
-- Check for working CXX compiler: /home/rete/soft/ilcsoft/v01-17-08/cernlib/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- CMAKE_MODULE_PATH : ;/home/rete/soft/DQM4HEP/testInstall/cmake;/home/rete/soft/DQM4HEP/testInstall/cmake;/home/rete/soft/DQM4HEP/testInstall/DQMViz/cmake
-- Check for ROOT_CONFIG_EXECUTABLE: /home/rete/soft/ilcsoft/v01-17-08/root/5.34.30/bin/root-config
-- Check for ROOT (5.34.30)
-- Check for ROOT_EXECUTABLE: /home/rete/soft/ilcsoft/v01-17-08/root/5.34.30/bin/root
-- Check for ROOT_CINT_EXECUTABLE: /home/rete/soft/ilcsoft/v01-17-08/root/5.34.30/bin/rootcint
-- Check for ROOT_LIBRARIES: Core;Cint;RIO;Net;Hist;Graf;Graf3d;Gpad;Tree;Rint;Postscript;Matrix;Physics;MathCore;Thread
-- Check for ROOT_COMPONENT_LIBRARIES: Core;Hist;Rint;HistPainter;Graf;Graf3d;MathCore;Net;RIO;Tree;QtRoot;GQt;Gui
-- Check for ROOT_CORE_LIBRARY: /home/rete/soft/ilcsoft/v01-17-08/root/5.34.30/lib/libCore.so -- ok
-- Check for ROOT_CINT_LIBRARY: /home/rete/soft/ilcsoft/v01-17-08/root/5.34.30/lib/libCint.so -- ok
-- Check for ROOT_RIO_LIBRARY: /home/rete/soft/ilcsoft/v01-17-08/root/5.34.30/lib/libRIO.so -- ok
-- Check for ROOT_NET_LIBRARY: /home/rete/soft/ilcsoft/v01-17-08/root/5.34.30/lib/libNet.so -- ok
-- Check for ROOT_HIST_LIBRARY: /home/rete/soft/ilcsoft/v01-17-08/root/5.34.30/lib/libHist.so -- ok
-- Check for ROOT_GRAF_LIBRARY: /home/rete/soft/ilcsoft/v01-17-08/root/5.34.30/lib/libGraf.so -- ok
-- Check for ROOT_GRAF3D_LIBRARY: /home/rete/soft/ilcsoft/v01-17-08/root/5.34.30/lib/libGraf3d.so -- ok
-- Check for ROOT_GPAD_LIBRARY: /home/rete/soft/ilcsoft/v01-17-08/root/5.34.30/lib/libGpad.so -- ok
-- Check for ROOT_TREE_LIBRARY: /home/rete/soft/ilcsoft/v01-17-08/root/5.34.30/lib/libTree.so -- ok
-- Check for ROOT_RINT_LIBRARY: /home/rete/soft/ilcsoft/v01-17-08/root/5.34.30/lib/libRint.so -- ok
-- Check for ROOT_POSTSCRIPT_LIBRARY: /home/rete/soft/ilcsoft/v01-17-08/root/5.34.30/lib/libPostscript.so -- ok
-- Check for ROOT_MATRIX_LIBRARY: /home/rete/soft/ilcsoft/v01-17-08/root/5.34.30/lib/libMatrix.so -- ok
-- Check for ROOT_PHYSICS_LIBRARY: /home/rete/soft/ilcsoft/v01-17-08/root/5.34.30/lib/libPhysics.so -- ok
-- Check for ROOT_MATHCORE_LIBRARY: /home/rete/soft/ilcsoft/v01-17-08/root/5.34.30/lib/libMathCore.so -- ok
-- Check for ROOT_THREAD_LIBRARY: /home/rete/soft/ilcsoft/v01-17-08/root/5.34.30/lib/libThread.so -- ok
-- Check for ROOT_CORE_LIBRARY: /home/rete/soft/ilcsoft/v01-17-08/root/5.34.30/lib/libCore.so -- ok
-- Check for ROOT_HIST_LIBRARY: /home/rete/soft/ilcsoft/v01-17-08/root/5.34.30/lib/libHist.so -- ok
-- Check for ROOT_RINT_LIBRARY: /home/rete/soft/ilcsoft/v01-17-08/root/5.34.30/lib/libRint.so -- ok
-- Check for ROOT_HISTPAINTER_LIBRARY: /home/rete/soft/ilcsoft/v01-17-08/root/5.34.30/lib/libHistPainter.so -- ok
-- Check for ROOT_GRAF_LIBRARY: /home/rete/soft/ilcsoft/v01-17-08/root/5.34.30/lib/libGraf.so -- ok
-- Check for ROOT_GRAF3D_LIBRARY: /home/rete/soft/ilcsoft/v01-17-08/root/5.34.30/lib/libGraf3d.so -- ok
-- Check for ROOT_MATHCORE_LIBRARY: /home/rete/soft/ilcsoft/v01-17-08/root/5.34.30/lib/libMathCore.so -- ok
-- Check for ROOT_NET_LIBRARY: /home/rete/soft/ilcsoft/v01-17-08/root/5.34.30/lib/libNet.so -- ok
-- Check for ROOT_RIO_LIBRARY: /home/rete/soft/ilcsoft/v01-17-08/root/5.34.30/lib/libRIO.so -- ok
-- Check for ROOT_TREE_LIBRARY: /home/rete/soft/ilcsoft/v01-17-08/root/5.34.30/lib/libTree.so -- ok
-- Check for ROOT_QTROOT_LIBRARY: /home/rete/soft/ilcsoft/v01-17-08/root/5.34.30/lib/libQtRoot.so -- ok
-- Check for ROOT_GQT_LIBRARY: /home/rete/soft/ilcsoft/v01-17-08/root/5.34.30/lib/libGQt.so -- ok
-- Check for ROOT_GUI_LIBRARY: /home/rete/soft/ilcsoft/v01-17-08/root/5.34.30/lib/libGui.so -- ok
-- Check for libdl.so: /usr/lib/i386-linux-gnu/libdl.so
-- Found ROOT: /home/rete/soft/ilcsoft/v01-17-08/root/5.34.30/include 
-- Looking for include files CMAKE_HAVE_PTHREAD_H
-- Looking for include files CMAKE_HAVE_PTHREAD_H - found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE 
-- Found streamlog: /home/rete/soft/DQM4HEP/testInstall 
-- Found JSONCpp: /usr/lib/libjsoncpp.so
-- Found DIM_SHARED: /home/rete/soft/dim/dim-git/linux/libdim.so 
-- Found DIM: /home/rete/soft/dim/dim-git/linux/libdim.so 
CMake Error at /home/rete/soft/ilcsoft/v01-17-08/CMake/2.8.5/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:91 (MESSAGE):
  Could NOT find DIMJC (missing: DIMJC_LIBRARIES DIMJC_INCLUDE_DIRS)
Call Stack (most recent call first):
  /home/rete/soft/ilcsoft/v01-17-08/CMake/2.8.5/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:252 (_FPHSA_FAILURE_MESSAGE)
  /home/rete/soft/DQM4HEP/testInstall/cmake/FindDIMJC.cmake:52 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:50 (FIND_PACKAGE)

-- Configuring incomplete, errors occurred!
CMakeFiles/DQMViz.dir/build.make:97: recipe for target 'DQMViz/src/DQMViz-stamp/DQMViz-configure' failed
make[2]: *** [DQMViz/src/DQMViz-stamp/DQMViz-configure] Error 1
CMakeFiles/Makefile2:408: recipe for target 'CMakeFiles/DQMViz.dir/all' failed
make[1]: *** [CMakeFiles/DQMViz.dir/all] Error 2
Makefile:79: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by apingault** [comment]
Typo in externalProject_add for dimjc. Fixed with commit 875251e

**Comment by rete** [comment]
Compiles again. Thanks !
